### ISSUE TITLE
There is no any filter in the video section

### ISSUE THREAD

**Issue by Dream5366** [KID-joker/userscript#1]

**Comment by KID-joker** [comment]
Can you show me the screenshot?

**Comment by KID-joker** [comment]
Here is a [preview](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/cdd55ebd994548ddb838b97353e27db0~tplv-k3u1fbpfcp-zoom-in-crop-mark:4536:0:0:0.awebp?), maybe it can solve your problem.
