### ISSUE TITLE
Range option does not work.

### ISSUE THREAD

**Issue by GaspacoZanis** [KID-joker/userscript#3]
If I try to enter the date, then I don't get the range of dates which I requested. Is it possible to fix this? 

Here is video of an issue I have:  https://youtu.be/KG9vNjvHpyQ

**Comment by KID-joker** [comment]
Do you mean show selected date range?

**Comment by GaspacoZanis** [comment]
> Do you mean show selected date range?

Yes. Date range option does not work correctly. In the example I have shown, I am searching for videos from February 1, 2021 until November 27, 2021. However, results show me videos from 2017, 2020, 2023, which is not what I asked for. Why?

**Comment by KID-joker** [comment]
@GaspacoZanis can you update v1.2.0 to check if it has been fixed

**Comment by GaspacoZanis** [comment]
@KID-joker Hello! I updated your program to v1.2.0. The issue is not fixed it seems like: https://youtu.be/7F-oeZR0_ZQ

As you can see, I updated your tool. Also I am testing this tool without having a bilibili account.

Is it possible to update the tool once more? Or what should I tool in order for this tool to work properly? Because I am still getting results which have nothing to do with the time interval indicated by me.
![Untitled](https://github.com/KID-joker/userscripts/assets/155786119/f5767422-7bb5-4c57-83b9-0880b5512105)

**Comment by KID-joker** [comment]
> @KID-joker Hello! I updated your program to v1.2.0. The issue is not fixed it seems like: https://youtu.be/7F-oeZR0_ZQ
> 
> As you can see, I updated your tool. Also I am testing this tool without having a bilibili account.
> 
> Is it possible to update the tool once more? Or what should I tool in order for this tool to work properly? Because I am still getting results which have nothing to do with the time interval indicated by me. ![Untitled](https://private-user-images.githubusercontent.com/155786119/321259950-f5767422-7bb5-4c57-83b9-0880b5512105.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTk3OTYsIm5iZiI6MTcxMjc1OTQ5NiwicGF0aCI6Ii8xNTU3ODYxMTkvMzIxMjU5OTUwLWY1NzY3NDIyLTdiYjUtNGM1Ny04M2I5LTA4ODBiNTUxMjEwNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNDMxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWQyZjgwZGM1Y2Q5NmI5ZDk4YzFkOGNiYmMwMDI5ODdlNmFkMTYxNTc4NTdhODg5NDM4OGVjMmNlYjNmYzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PzOesfRaAycSEuMotpXje6rAWwnVolb2ZCaCWTGnFg8)

![image](https://github.com/KID-joker/userscripts/assets/42445388/f28184e3-34b6-4a5d-9b56-47996c82bd84)
it's so weird!!

**Comment by KID-joker** [comment]
@GaspacoZanis What browser and extension are you using?

**Comment by GaspacoZanis** [comment]
@KID-joker 
- Firefox browser
- Violentmonkey 2.18.0 extension for your script  (you can see in previous screenshot how it is installed)
- Bilibili site I am using without account

**Comment by KID-joker** [comment]
![image](https://github.com/KID-joker/userscripts/assets/42445388/038e59a5-5b56-4fe9-911f-2cd1230ac03a)
it can also be used with firefox and violentmonkey.
Can you open the console panel to provide more information?
![image](https://github.com/KID-joker/userscripts/assets/42445388/a15e9d83-ab1b-44bf-9d12-803636328750)
Or you can try Chrome and tampermonkey.

**Comment by GaspacoZanis** [comment]
@KID-joker https://youtu.be/UZQDKe4ketE this is what I see in the console. Does it help resolving the issue for Firefox?

**Comment by KID-joker** [comment]
@GaspacoZanis Hello, what IM are you using? Discord or else?

**Comment by GaspacoZanis** [comment]
A bit late reply, but I do have Discord! It is: GaspacoZanis
@KID-joker

**Comment by GaspacoZanis** [comment]
It seems like Bilibili had an update to add date option? So I guess the problem is resolved
