### ISSUE TITLE
脚本无法和官方综合排序里的最新发布同时生效

### ISSUE THREAD

**Issue by KwToPA** [KID-joker/userscript#6]
我想搜索特定时间内的视频，结果按照时间倒序排列

但脚本无法和官方综合排序里的最新发布同时生效，综合排序里面其余三个都可以和脚本协同作业

另，脚本反馈的默认结果无法铺满一个页面，需要点击下一页才能浏览，搭配综合排序的其余三个标签，反馈的结果可以铺满整个页面

**Comment by KID-joker** [comment]
铺满页面的问题是因为B站设置了请求10秒超时，所以有几个请求数量少，也必须在10秒内返回结果
