### ISSUE TITLE
用不了了啊？换成edge，谷歌游览器的插件都试了，没反应啊

### ISSUE THREAD

**Issue by fs1314** [KID-joker/userscript#7]
![QQ截图20240811204957](https://github.com/user-attachments/assets/f0ad4413-9467-4e37-903c-7c4a28bb6847)

**Comment by KID-joker** [comment]
换到视频分类

**Comment by fs1314** [comment]
> 换到视频分类

我的我的，弄了半天原来是这个原因/_ \
